### ISSUE TITLE
Notifications for apps that haven't been updated

### ISSUE THREAD

**Issue by lpinner** [farmerbb/AppNotifier#2]
I've had a few notifications about apps that haven't been updated recently

AppNotifier Notification:
![Screenshot_20200204-012712~2](https://user-images.githubusercontent.com/4827816/73687498-4dea1980-471e-11ea-85bf-cb5286095cd8.png)

App last updated Oct 2019:
![Screenshot_20200204-012919~2](https://user-images.githubusercontent.com/4827816/73687514-58a4ae80-471e-11ea-9223-6fc82ced7400.png)

App last updated Dec 2019:
![Screenshot_20200204-012744~2](https://user-images.githubusercontent.com/4827816/73687527-5fcbbc80-471e-11ea-83ed-1f9c270241fe.png)

Phone is a stock Motorola G6plus Android 9.

If there's anything else I can provide to assist, just let me know.

**Comment by farmerbb** [comment]
Thanks, this is an issue that I and a few others have seen intermittently.

Assuming you haven't rebooted your phone, do you mind [pulling a logcat](https://www.makeuseof.com/tag/get-logcat-reporting-bugs-android/) from your device and then emailing that to me?

**Comment by lpinner** [comment]
Sent, thanks.

**Comment by farmerbb** [comment]
I just published version 1.2.1 which contains a fix for this issue.
